SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cbLock](
	[cbSPID] [smallint] NOT NULL,
	[cbDb] [int] NOT NULL,
	[cbFile] [int] NOT NULL,
	[cbType] [smallint] NOT NULL,
	[cbMarq] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_cbLock_cbMarq] ON [dbo].[cbLock]
(
	[cbDb] ASC,
	[cbFile] ASC,
	[cbMarq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_cbLock_cbType] ON [dbo].[cbLock]
(
	[cbDb] ASC,
	[cbFile] ASC,
	[cbType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [dbo].[cbLock] ADD  CONSTRAINT [DF_cbLock_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO